name: dart_falconnect
description: A new Flutter package project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  dart_falmodel:
    path: ../dart_falmodel
  dart_faltool:
    path: ../dart_faltool

  #PLATFORM: All
  ansicolor: ^2.0.3
  dio: ^5.9.0
  retrofit: ^4.7.2
  web_socket_channel: ^3.0.3
  dio_cache_interceptor: ^4.0.3
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  test: ^1.26.3
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  retrofit_generator: ^10.0.5
  very_good_analysis: ^10.0.0
