name: dart_faltool
description: A tools library for Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  dart_falmodel:
    path: ../dart_falmodel

  #PLATFORM: All
  ansicolor: ^2.0.3
  crypto: ^3.0.6
  dartx: ^1.2.0
  enum_to_string: ^2.2.1
  equatable: ^2.0.7
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  numeral: ^3.1.1
  retry: ^3.1.2
  rxdart: ^0.28.0
  stack_trace: ^1.12.1
  timeago: ^3.7.1
  uuid: ^4.5.1
  version: ^3.0.2
  web: ^1.1.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.7.0
  test: ^1.26.3
  very_good_analysis: ^9.0.0
