name: dart_falconx
description: A dart falcon package.
version: 2.4.0
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  dart_falconnect:
    git:
      url: https://github.com/Nextzy/dart-falconx
      ref: 2.4.0
      path: dart_falconnect
  dart_falmodel:
    git:
      url: https://github.com/Nextzy/dart-falconx
      ref: 2.4.0
      path: dart_falmodel
  dart_faltool:
    git:
      url: https://github.com/Nextzy/dart-falconx
      ref: 2.4.0
      path: dart_faltool

dev_dependencies:
  lints: ^6.1.0
  test: ^1.32.0
  very_good_analysis: ^11.0.0
  yaml: ^3.1.4
