name: dart_falconx
description: A dart falcon package.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  dart_falconnect:
    path: ../dart_falconnect
  dart_falmodel:
    path: ../dart_falmodel
  dart_faltool:
    path: ../dart_faltool

dev_dependencies:
  lints: ^6.1.0
  test: ^1.32.0
  very_good_analysis: ^11.0.0
